import {PropsListProps} from "./StyleProps"

export const propsList: PropsListProps[] = [
  {
    id: "background",
    props: [
      ["background", "background"],
      ["backgroundImage", "background-image"],
      ["backgroundSize", "background-size"],
      ["backgroundPosition", "background-position"],
      ["backgroundRepeat", "background-repeat"],
    ],
  },
  {
    id: "border",
    props: [
      ["border", "border", "borders"],
      ["borderWidth", "border-width", "borderWidths"],
      ["borderStyle", "border-style", "borderStyles"],
      ["borderColor", "border-color", "colors"],
      ["borderRadius", "border-radius", "radii"],
      ["borderTop", "border-top", "borders"],
      ["borderTopWidth", "border-top-width", "borderWidths"],
      ["borderTopStyle", "border-top-style", "borderStyles"],
      ["borderTopColor", "border-top-color", "colors"],
      ["borderTopLeftRadius", "border-top-left-radius", "radii"],
      ["borderTopRightRadius", "border-top-right-radius", "radii"],
      ["borderRight", "border-right", "borders"],
      ["borderRightWidth", "border-right-width", "borderWidths"],
      ["borderRightStyle", "border-right-style", "borderStyles"],
      ["borderRightColor", "border-right-color", "colors"],
      ["borderBottom", "border-bottom", "borders"],
      ["borderBottomWidth", "border-bottom-width", "borderWidths"],
      ["borderBottomStyle", "border-bottom-style", "borderStyles"],
      ["borderBottomColor", "border-bottom-color", "colors"],
      ["borderBottomLeftRadius", "border-bottom-left-radius", "radii"],
      ["borderBottomRightRadius", "border-bottom-right-radius", "radii"],
      ["borderLeft", "border-left", "borders"],
      ["borderLeftWidth", "border-left-width", "borderWidths"],
      ["borderLeftStyle", "border-left-style", "borderStyles"],
      ["borderLeftColor", "border-left-color", "colors"],
      ["borderX", "border-left, border-right", "borders"],
      ["borderY", "border-top, border-bottom", "borders"],
      ["outline", "outline"],
      ["outlineColor", "outline-color", "colors"],
      ["outlineWidth", "outline-width"],
      ["outlineStyle", "outline-style"],
    ],
  },
]
