import {PropsListProps} from "./PropGroup"

export const propsList: PropsListProps[] = [
  {
    id: "background",
    props: [
      ["background", "background"],
      ["backgroundImage", "background-image"],
      ["backgroundSize", "background-size"],
      ["backgroundPosition", "background-position"],
      ["backgroundRepeat", "background-repeat"],
    ],
  },
  {
    id: "border",
    props: [
      ["border", "border", "borders"],
      ["borderWidth", "border-width", "borderWidths"],
      ["borderStyle", "border-style", "borderStyles"],
      ["borderColor", "border-color", "colors"],
      ["borderRadius", "border-radius", "radii"],
      ["borderTop", "border-top", "borders"],
      ["borderTopWidth", "border-top-width", "borderWidths"],
      ["borderTopStyle", "border-top-style", "borderStyles"],
      ["borderTopColor", "border-top-color", "colors"],
      ["borderTopLeftRadius", "border-top-left-radius", "radii"],
      ["borderTopRightRadius", "border-top-right-radius", "radii"],
      ["borderRight", "border-right", "borders"],
      ["borderRightWidth", "border-right-width", "borderWidths"],
      ["borderRightStyle", "border-right-style", "borderStyles"],
      ["borderRightColor", "border-right-color", "colors"],
      ["borderBottom", "border-bottom", "borders"],
      ["borderBottomWidth", "border-bottom-width", "borderWidths"],
      ["borderBottomStyle", "border-bottom-style", "borderStyles"],
      ["borderBottomColor", "border-bottom-color", "colors"],
      ["borderBottomLeftRadius", "border-bottom-left-radius", "radii"],
      ["borderBottomRightRadius", "border-bottom-right-radius", "radii"],
      ["borderLeft", "border-left", "borders"],
      ["borderLeftWidth", "border-left-width", "borderWidths"],
      ["borderLeftStyle", "border-left-style", "borderStyles"],
      ["borderLeftColor", "border-left-color", "colors"],
      ["borderX", "border-left & border-right", "borders"],
      ["borderY", "border-top & border-bottom", "borders"],
      ["outline", "outline"],
      ["outlineColor", "outline-color", "colors"],
      ["outlineWidth", "outline-width"],
      ["outlineStyle", "outline-style"],
    ],
  },
  {
    id: "color",
    props: [
      ["color", "color", "colors"],
      ["backgroundColor, bg", "background-color", "colors"],
      ["opacity", "opacity"],
    ],
  },
  {
    id: "display",
    props: [["display", "display"]],
  },
  {
    id: "flex",
    props: [
      ["alignItems", "align-items"],
      ["alignContent", "align-content"],
      ["justifyItems", "justify-items"],
      ["justifyContent", "justify-content"],
      ["flexWrap", "flex-wrap"],
      ["flexDirection", "flex-direction"],
      ["flex", "flex"],
      ["flexGrow", "flex-grow"],
      ["flexShrink", "flex-shrink"],
      ["flexBasis", "flex-basis"],
      ["justifySelf", "justify-self"],
      ["alignSelf", "align-self"],
      ["order", "order"],
    ],
  },
  {
    id: "grid",
    props: [
      ["gridGap", "grid-gap", "space"],
      ["gridColumnGap", "grid-column-gap", "space"],
      ["gridRowGap", "grid-row-gap", "space"],
      ["gridColumn", "grid-column"],
      ["gridRow", "grid-row"],
      ["gridAutoFlow", "grid-auto-flow"],
      ["gridAutoColumns", "grid-auto-columns"],
      ["gridAutoRows", "grid-auto-rows"],
      ["gridTemplateColumns", "grid-template-columns"],
      ["gridTemplateRows", "grid-template-rows"],
      ["gridTemplateAreas", "grid-template-areas"],
      ["gridArea", "grid-area"],
    ],
  },
  {
    id: "interactivity",
    props: [
      ["appearance", "appearance"],
      ["cursor", "cursor"],
      ["pointerEvents", "pointer-events"],
      ["resize", "resize"],
      ["userSelect", "user-select"],
    ],
  },
  {
    id: "layout",
    props: [
      ["bottom", "bottom"],
      ["boxSizing", "box-sizing"],
      ["left", "left"],
      ["objectFit", "object-fit"],
      ["overflow", "overflow"],
      ["overflowX", "overflow-x"],
      ["overflowY", "overflow-y"],
      ["overscrollBehavior", "overscroll-behavior"],
      ["position", "position"],
      ["right", "right"],
      ["top", "top"],
      ["visibility", "visibility"],
      ["zIndex", "z-index"],
    ],
  },
  {
    id: "shadows",
    props: [
      ["boxShadow", "box-shadow", "shadows"],
      ["textShadow", "text-shadow", "shadows"],
    ],
  },
  {
    id: "sizing",
    props: [
      ["height", "height", "sizes"],
      ["width", "width", "sizes"],
      ["maxHeight", "max-height"],
      ["minHeight", "min-height"],
      ["maxWidth", "max-width"],
      ["minWidth", "min-width"],
    ],
  },
  {
    id: "space",
    props: [
      ["margin / m", "margin", "space"],
      ["marginTop / mt", "margin-top", "space"],
      ["marginRight / mr", "margin-right", "space"],
      ["marginBottom / mb", "margin-bottom", "space"],
      ["marginLeft / ml", "margin-left", "space"],
      ["marginX / mx", "margin-right & margin-left", "space"],
      ["marginY / my", "margin-top & margin-bottom", "space"],
      ["padding / p", "padding", "space"],
      ["paddingTop / pt", "padding-top", "space"],
      ["paddingRight / pr", "padding-right", "space"],
      ["paddingBottom / pb", "padding-bottom", "space"],
      ["paddingLeft / pl", "padding-left", "space"],
      ["paddingX / px", "padding-right & padding-left", "space"],
      ["paddingY / py", "padding-top & padding-bottom", "space"],
    ],
  },
  {
    id: "transitions",
    props: [
      ["transform", "transform"],
      ["transformBox", "transform-box"],
      ["transformOrigin", "transform-origin"],
      ["transformStyle", "transform-style"],
      ["transition", "transition"],
      ["transitionDelay", "transition-delay"],
      ["transitionDuration", "transition-duration"],
      ["transitionProperty", "transition-property"],
      ["transitionTimingFunction", "transition-timing-function"],
      ["willChange", "will-change"],
    ],
  },
  {
    id: "typography",
    props: [
      ["fontFamily", "font-family", "fonts"],
      ["fontSize", "font-size", "fontSizes"],
      ["fontWeight", "font-weight", "fontWeights"],
      ["lineHeight", "line-height", "lineHeights"],
      ["letterSpacing", "letter-spacing", "letterSpacings"],
      ["textAlign", "text-align"],
      ["fontStyle", "font-style"],
      ["listStyleType", "list-style-type"],
      ["listStylePosition", "list-style-position"],
      ["textDecoration", "text-decoration"],
      ["textOverflow", "text-overflow"],
      ["textShadow", "text-shadow"],
      ["textTransform", "text-transform"],
      ["whiteSpace", "white-space"],
      ["wordBreak", "word-break"],
    ],
  },
]
